
preview_url: "{{ adanos_view_link }}"
grpc_listen: "{{ adanos_grpc_listen }}"
grpc_token: "{{ adanos_grpc_token }}"
mongo_uri: "{{ adanos_mongo_uri }}"
mongo_db: "{{ adanos_mongo_db }}"
api_token: "{{ adanos_api_token }}"
enable_migrate: {{ adanos_enable_migrate }}
listen: "{{ adanos_listen }}"
keep_period: 14

aliyun_voice_called_show_number: "{{ adanos_aliyun_voice_called_show_number }}"
aliyun_voice_tts_code: "{{ adanos_aliyun_voice_tts_code }}"
aliyun_voice_tts_param: "{{ adanos_aliyun_voice_tts_param }}"
aliyun_access_key: "{{ adanos_aliyun_access_key }}"
aliyun_access_secret: "{{ adanos_aliyun_access_secret }}"