---
- name: create user adanos
  user:
    name: adanos
    shell: /sbin/nologin
    state: present

- name: create directory
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
    follow: true
  with_items:
    - /usr/local/adanos-alert/bin
    - /usr/local/adanos-alert/etc

- name: create work directory
  file:
    path: "{{ item }}"
    state: directory
    owner: adanos
    follow: true
  with_items:
    - /usr/local/adanos-alert/data

- name: install adanos-alert-server
  copy:
    src: adanos-alert-server
    dest: /usr/local/adanos-alert/bin/adanos-alert-server
    mode: 0755
  tags:
    - install_adanos_alert_server_bin
    - install_adanos_alert_server

- name: copy adanos-server config files
  template:
    src: server.yaml
    dest: /usr/local/adanos-alert/etc/server.yaml
  tags:
    - copy_adanos_alert_server_config
    - install_adanos_alert_server

- name: copy systemd file for adanos server
  template:
    src: adanos-alert-server.service
    dest: /usr/lib/systemd/system/adanos-alert-server.service
  tags:
    - create_adanos_alert_server_systemd
    - install_adanos_alert_server

- name: reload adanos alert service
  systemd:
    name: adanos-alert-server
    daemon_reload: true
    enabled: yes
    state: restarted
  tags:
    - restart_adanos_alert_server_service
    - install_adanos_alert_server